my_shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.home, name='home'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('contacts/', views.contacts, name='contacts'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/profile/', views.profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('create_order/', views.create_order, name='create_order'),
]

my_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('my_shop.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_shop/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Order, UserProfile

class UserRegistrationForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    phone_number = forms.CharField(max_length=15, required=False)
    email = forms.EmailField(required=False)
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone_number', 'email', 'password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        if password != password_confirm:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            UserProfile.objects.create(
                user=user,
                phone_number=self.cleaned_data.get('phone_number')
            )
        return user

class OrderForm(forms.ModelForm):
    shipping_address = forms.CharField(label='Адреса доставки', widget=forms.Textarea)
    additional_phone_number = forms.CharField(label='Додатковий номер телефону', max_length=15, required=False)

    class Meta:
        model = Order
        fields = ['shipping_address', 'additional_phone_number']

    def save(self, user=None, cart=None, commit=True):
        if user is None or cart is None:
            raise ValueError("Користувач і кошик повинні бути надані.")

        order = super().save(commit=False)
        order.user = user
        order.first_name = user.first_name
        order.last_name = user.last_name
        if commit:
            order.save()
            for item in cart.items.all():
                order.products.add(item.product)
            cart.delete()
        return order

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}PRO-DS{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
<header>
  <div class="container">
    <h1><a href="/">PRO-DS</a></h1>
    <nav>
      <ul>
        <li><a href="{% url 'contacts' %}">Контакти</a></li>
        {% if request.user.is_authenticated %}
          <li><a href="{% url 'view_cart' %}">Корзина</a></li>
          <li><a href="{% url 'profile' %}">Привіт, {{ request.user.username }}</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">Увійти</a></li>
          <li><a href="{% url 'register' %}">Реєстрація</a></li>
        {% endif %}
        <!-- Додайте більше посилань, якщо потрібно -->
      </ul>
    </nav>
  </div>
</header>

<main>
  <div class="container">
    {% block content %}
      <!-- Вміст дочірніх шаблонів буде вставлено тут -->
    {% endblock %}
  </div>
</main>

<footer>
  <div class="container">
    <p>&copy; 2024 PRO-DS. Усі права захищені.</p>
  </div>
</footer>

<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/cart.html
<!-- Оновлений шаблон cart.html -->
{% extends 'base.html' %}

{% block title %}Корзина покупок{% endblock %}

{% block content %}
<div class="cart-container">
    <h2>Корзина</h2>
    {% if cart_items %}
        <ul>
            {% for item in cart_items %}
                <li>
                    {{ item.product.name }} - {{ item.quantity }} x {{ item.product.price }}
                    <a href="{% url 'remove_from_cart' item.id %}">Видалити</a> <!-- Посилання на видалення товару -->
                </li>
            {% endfor %}
        </ul>
        <p>Загальна ціна: {{ total }}</p>
        <form method="post" action="{% url 'create_order' %}">
            {% csrf_token %}
            <button type="submit">Створити замовлення</button>
        </form>
    {% else %}
        <p>Твоя корзина пуста.</p>
    {% endif %}
    <a href="javascript:history.back()">Назад</a>
</div>
{% endblock %}

templates/category_detail.html
{% extends 'base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/category_detail.css' %}"> <!-- Підключення CSS файлу -->

<style>
  .product-image {
    width: 100%;
    height: 280px; /* Задаємо фіксовану висоту */
    display: block;
    object-fit: contain; /* Вписуємо зображення в контейнер без спотворення пропорцій */
    margin: 0;
  }
</style>
<div class="category-container">
  <h2>{{ category.name }}</h2>
  <form method="get" action="{% url 'category_detail' category.id %}">
    <div class="sort-filter-container">
      <div class="sort-section">
        <h2>Сортувати за:</h2>
        <select name="sort_by" id="sort_by">
          <option value="name" {% if request.GET.sort_by == 'name' %}selected{% endif %}>Назвою</option>
          <option value="price_asc" {% if request.GET.sort_by == 'price_asc' %}selected{% endif %}>Ціною: від низької</option>
          <option value="price_desc" {% if request.GET.sort_by == 'price_desc' %}selected{% endif %}>Ціною: від високої</option>
        </select>
      </div>
      <div class="form-group search-section">
        <input type="text" name="search" id="search" placeholder="Введіть назву товару" value="{{ request.GET.search }}">
      </div>
      <button type="submit" class="sort-filter-button">Пошук</button>
    </div>
  </form>
  <ul class="product-list row">
    {% for product in products %}
    <li class="col-lg-4 col-md-6 mb-4">
      <div class="card">
        <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light" data-mdb-ripple-color="light">
          <a href="{% url 'product_detail' product.id %}">
            <img src="{{ product.images.first.image.url }}" class="product-image" alt="{{ product.name }}"/>
            <div class="hover-overlay">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
            </div>
          </a>
        </div>
        <div class="card-body">
          <a href="{% url 'product_detail' product.id %}" class="text-reset">
            <h5 class="card-title mb-3">{{ product.name }}</h5>
          </a>
          <h6 class="mb-3">{{ product.price }} грн.</h6>
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
  {% if products.has_other_pages %}
  <div class="pagination">
    <span class="step-links">
      {% if products.has_previous %}
      <a href="?page=1{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">&laquo; перша</a>
      <a href="?page={{ products.previous_page_number }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">повередня</a>
      {% endif %}
      <span class="current">
        Сторінка {{ products.number }} з {{ products.paginator.num_pages }}.
      </span>
      {% if products.has_next %}
      <a href="?page={{ products.next_page_number }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">наступна</a>
      <a href="?page={{ products.paginator.num_pages }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">остання &raquo;</a>
      {% endif %}
    </span>
  </div>
  {% endif %}
</div>
{% endblock %}

templates/contacts.html
{% extends 'base.html' %}

{% block title %}Контакти{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contacts.css' %}">
<h2>Контакти</h2>
<ul>
    <p>Графік роботи</p>
    <li>Пн - Пт: 9.00 по 19.00</li>
    <li>Сб: 10.00 по 18.00</li>
    <li>Нд: 11.00 по 17.00</li>
</ul>
<ul>
    <p>Зв'яжіться з нами:</p>
    <li>Телефон: +380989902010</li>
    <li>Телефон: +380739902010</li>
    <li>Телефон: +380937411777</li>

    <li>Адреса: м.Львів, вул. Вільхова 11</li>
</ul>
<a href="javascript:history.back()">Назад</a>
{% endblock %}

templates/create_order.html
{% extends 'base.html' %}

{% block title %}Створення замовлення{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/create_order.css' %}">

<div class="container">
    <h1>Створення замовлення</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="user" value="{{ request.user.id }}">
        <input type="hidden" name="cart" value="{% if request.user.has_cart %}{{ request.user.cart.id }}{% endif %}">
        <label for="id_shipping_address">Адреса доставки:</label><br>
        {{ form.shipping_address }}
        <br><br>
        <!-- Додайте поле для введення номеру телефону -->
        <label for="id_additional_phone_number">Номер телефону:</label><br>
        {{ form.additional_phone_number }}
        <br><br>
        <button type="submit">Замовити</button>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Головна сторінка{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

<h2>Магазин побутової техніки PRO-DS</h2>
<ul class="categories-list">
  {% for category in categories %}
    <li>
      <div class="category-item">
        <a href="{% url 'category_detail' category.id %}">
          <img src="{{ category.photo.url }}" alt="{{ category.name }} Photo" class="category-image">
          <p>{{ category.name }}</p>
        </a>
      </div>
    </li>
  {% endfor %}
</ul>
{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/product_detail.css' %}"> <!-- Підключення CSS файлу -->

<h1>{{ product.name }}</h1>

{% if product.images.count > 0 %}
  <div class="slider">
    <div class="slider-images">
      {% for image in product.images.all %}
        <img class="slide" src="{{ image.image.url }}" alt="{{ product.name }} Image">
      {% endfor %}
    </div>
    <a class="prev" onclick="moveSlide(-1)">&#10094;</a>
    <a class="next" onclick="moveSlide(1)">&#10095;</a>
  </div>
{% endif %}

<p><strong>Категорія:</strong> {{ product.category }}</p>
<p><strong>Опис:</strong><br> {{ product.description|linebreaks }}</p>
<p><strong>Артикул:</strong> {{ product.article }}</p>
<p><strong>Ціна:</strong> {{ product.price }} грн.</p>

<form method="post" action="{% url 'add_to_cart' product.id %}">
  {% csrf_token %}
  <button type="submit">Добавити в корзину</button>
</form>

<a href="javascript:history.back()">Назад</a>

<script src="{% static 'js/slider.js' %}"></script> <!-- Підключення JS файлу -->
{% endblock %}